### ISSUE TITLE
Update Sorrentum dev container

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#716]
https://github.com/sorrentum/sorrentum/blob/master/sorrentum_sandbox/README.md#sorrentum-system-container

I've updated to the latest image of Airflow, built the container (instead of 2.2.2)

```
  2 #FROM apache/airflow:2.2.2
  3 FROM apache/airflow:latest
```

and docker_bash.sh doesn't work

```
$ airflow db check                                                                                                                     /home/airflow/.local/lib/python3.11/site-packages/airflow/configuration.py:812 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.11/site-packages/airflow/configuration.py:738 DeprecationWarning: The sql_alchemy_conn option in [core
] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.          /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.11/site-packages/airflow/models/base.py:71 DeprecationWarning: The sql_alchemy_conn option in [core] h
as been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-06T21:59:27.817+0000] {cli_action_loggers.py:135} WARNING - Failed to log action (psycopg2.OperationalError) connection to server at "host.docker.internal" (192.168.65.254), port 5532 failed: Connection refused                                                           Is the server running on that host and accepting TCP/IP connections?
...
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "host.docker.internal" (192.168.65.254), port 5532
 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
```

**Comment by gpsaggese** [comment]
The first version of the container with both x86 and arm image is apache/airflow:2.8.0-python3.9

**Comment by gpsaggese** [comment]
It still gives the same error but let me see if `docker-compose up` works

**Comment by gpsaggese** [comment]
Uhm... Airflow doesn't seem to come up

```
airflow_cont         | ERROR: You need to initialize the database. Please run `airflow db init`. Make sure the command is run using Airflow version 2.8.0.
```

**Comment by samarth9008** [comment]
2 problems for now to run the examples

Although the setup for now is build by for some unknown reason it is taking backed as SQLLite and not our postgres container. The problem with sqlite is that it only works with SequentialExecutor so no airflow dags are being executed. Will have to figure out why the back postgres is not being used


Another problem is while executing the command over here to get the data from binance
https://github.com/sorrentum/sorrentum/tree/master/sorrentum_sandbox#download-data

It gives permission denied error

```
sorrentum@samarthkp:~/src/sorrentum1/sorrentum_sandbox/devops$ ./docker_bash.sh 
++ git rev-parse --show-toplevel
+ GIT_ROOT=/home/sorrentum/src/sorrentum1
+++ dirname -- ./docker_bash.sh
++ cd -- .
++ pwd
+ SCRIPT_DIR=/home/sorrentum/src/sorrentum1/sorrentum_sandbox/devops
+ DOCKER_NAME=/home/sorrentum/src/sorrentum1/sorrentum_sandbox/devops/docker_name.sh
+ [[ ! -e /home/sorrentum/src/sorrentum1/sorrentum_sandbox/devops ]]
+ source /home/sorrentum/src/sorrentum1/sorrentum_sandbox/devops/docker_name.sh
++ REPO_NAME=sorrentum
++ IMAGE_NAME=sorrentum
++ FULL_IMAGE_NAME=sorrentum/sorrentum
+ docker image ls sorrentum/sorrentum
REPOSITORY            TAG       IMAGE ID       CREATED        SIZE
sorrentum/sorrentum   latest    829237545c73   24 hours ago   4.46GB
+ CONTAINER_NAME=sorrentum
+ docker run --rm -ti --name sorrentum -v /home/sorrentum/src/sorrentum1:/cmamp --env-file .env sorrentum/sorrentum bash

airflow@48c22b8f2240:/opt/airflow$ cd /cmamp/sorrentum_sandbox/examples/systems/binance
airflow@48c22b8f2240:/cmamp/sorrentum_sandbox/examples/systems/binance$ ./download_to_csv.py --start_timestamp '2022-10-20 10:00:00+00:00' --end_timestamp '2022-10-21 15:30:00+00:00' --target_dir 'binance_data'
INFO: > cmd='./download_to_csv.py --start_timestamp 2022-10-20 10:00:00+00:00 --end_timestamp 2022-10-21 15:30:00+00:00 --target_dir binance_data'
Traceback (most recent call last):
  File "/cmamp/sorrentum_sandbox/examples/systems/binance/./download_to_csv.py", line 129, in <module>
    _main(_parse())
  File "/cmamp/sorrentum_sandbox/examples/systems/binance/./download_to_csv.py", line 113, in _main
    hdbg.init_logger(
  File "/cmamp/helpers/hdbg.py", line 1007, in init_logger
    file_handler = logging.FileHandler(log_filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/cmamp/sorrentum_sandbox/examples/systems/binance/download_to_csv.py.log'
airflow@48c22b8f2240:/cmamp/sorrentum_sandbox/examples/systems/binance$ 
```

**Comment by samarth9008** [comment]
PR for this - https://github.com/sorrentum/sorrentum/pull/724

**Comment by samarth9008** [comment]
The first problem is resolved but the due to the second problem, the related dags are not running successfully. Giving same errors in the airflow logs.

**Comment by gpsaggese** [comment]
I've tried but I still don't see Airflow starting.

```
postgres_cont        | 2024-03-10 12:24:58.953 UTC [46] ERROR:  relation "log" does not exist at character 13
postgres_cont        | 2024-03-10 12:24:58.953 UTC [46] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-03-10T12:24:58.934306+00:00'::timestamptz, 'cli_we
bserver', 'airflow', '{"host_name": "39389abd94a2", "full_command": "[''/home/airflow/.local/bin/airflow'', ''webserver'']"}') RETURNING log.id                                 airflow_cont         | ERROR: You need to initialize the database. Please run `airflow db init`. Make sure the command is run using Airflow version 2.8.2.
```

I would

1) Ping the Airflow version to something recent but not latest, otherwise next year will have to debug another problem

2) We should use Postgres as backend

3) The set up that would make sense is to initialize the DB while building the container so that we simplify the flow

**Comment by samarth9008** [comment]
Can you try one more thing if you haven't. A change in sequence


Run docker-compose up

Once the container are up, run init airflow setup script in a different terminal before trying to login


I think airflow will only work if you have setup db in all the containers. Doesn't matter if its, webserver or scheduler.

**Comment by gpsaggese** [comment]
This was done. Thanks @samarth9008
